In [1]:
import numpy as np

In [4]:
# Vektor
a = np.array([0,1,2,3])
print('a:', a)

a: [0 1 2 3]


In [5]:
# Vektor
b = np.array([4,5,6,7])
print('b:', b)

b: [4 5 6 7]


In [6]:
# Matrix
c = np.array([
    [0,1,2,3],
    [4,5,6,7]
])
print('c:', c)

c: [[0 1 2 3]
 [4 5 6 7]]


In [7]:
# Matrix mit Nullen
d = np.zeros((2,4))
print('d:', d)

d: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Matrix mit Random zwischen 0-1
e = np.random.rand(2,5)
print('e:', e)

e: [[0.87213743 0.93597202 0.27365015 0.17673281 0.26315459]
 [0.30535385 0.80736728 0.56820761 0.41038572 0.67890747]]


In [15]:
# Multipliziert alle Zahlen im Vektor a
print('a:', a)
print('a * 0.1:', a * 0.1)

a: [0 1 2 3]
a * 0.1: [0.  0.1 0.2 0.3]


In [14]:
# Multipliziert alle Zahlen in der Matrix c
print('c:', c)
print('c * 0.2:', c * 0.2)

c: [[0 1 2 3]
 [4 5 6 7]]
c * 0.2: [[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]


In [12]:
# Elementarweise Multiplikation von Vec a und Vec b
print('a:', a)
print('b:', b)
print('a * b:', a * b)

a: [0 1 2 3]
b: [4 5 6 7]
a * b: [ 0  5 12 21]


In [16]:
# Elementarweise Multiplikation von Vec a und Vec b anschliessend * 0.2
print('a * b * 0.2:', a * b * 0.2)

a * b * 0.2: [0.  1.  2.4 4.2]


In [17]:
# Elementarweise Multiplikation von Vec a und der Zeilen von Matrix c (denn Anz. Spalten = Anz. Zahlen Vec)
print('a * c:', a * c)

a * c: [[ 0  1  4  9]
 [ 0  5 12 21]]
